# Configuración de H2
spring.datasource.url=jdbc:h2:mem:fightsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Para que Spring cree las tablas automáticamente basándose en tus clases @Entity
spring.jpa.hibernate.ddl-auto=update

# Para ver las consultas SQL en la consola (muy útil para aprender)
spring.jpa.show-sql=true

# Activa la consola
spring.h2.console.enabled=true

# Define una ruta fija (más fácil de recordar)
spring.h2.console.path=/h2-console